"""Initial migration

Revision ID: 39654861a8ad
Revises: 
Create Date: 2026-01-10 21:20:27.450450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39654861a8ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailed_plans')
    op.drop_table('notification_preferences')
    op.alter_column('assignments', 'week_plan_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='Reference to week plan if this assignment is part of a weekly plan',
               existing_nullable=True)
    op.alter_column('assignments', 'day_of_week',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Day of week (1=Monday, 7=Sunday) for weekly plans',
               existing_nullable=True)
    op.alter_column('assignments', 'sets',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of sets for this exercise',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('assignments', 'rest_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Rest time between sets in seconds',
               existing_nullable=True,
               existing_server_default=sa.text('60'))
    op.drop_index(op.f('idx_assignments_day_of_week'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_week_plan'), table_name='assignments')
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignments_patient_id'), 'assignments', ['patient_id'], unique=False)
    op.drop_constraint(op.f('assignments_week_plan_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'week_plans', ['week_plan_id'], ['plan_id'])
    op.create_index(op.f('ix_brain_exercise_logs_log_id'), 'brain_exercise_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_brain_exercise_sessions_session_id'), 'brain_exercise_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_combo_items_item_id'), 'combo_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_combos_combo_id'), 'combos', ['combo_id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_date'), 'exercise_logs_simple', ['date'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_id'), 'exercise_logs_simple', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_user_id'), 'exercise_logs_simple', ['user_id'], unique=False)
    op.alter_column('medical_records', 'blood_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.create_index(op.f('ix_medical_records_record_id'), 'medical_records', ['record_id'], unique=False)
    op.create_unique_constraint(None, 'medical_records', ['patient_id'])
    op.drop_column('medical_records', 'allergies')
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.alter_column('patient_notes', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_patient_notes_note_id'), 'patient_notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_schedules_schedule_id'), 'schedules', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_session_details_detail_id'), 'session_details', ['detail_id'], unique=False)
    op.drop_index(op.f('idx_users_full_name'), table_name='users')
    op.drop_constraint(op.f('users_full_name_unique'), 'users', type_='unique')
    op.alter_column('week_plans', 'plan_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('week_plans', 'plan_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='Name of the workout plan',
               existing_nullable=False)
    op.alter_column('week_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Status of the plan: active, completed, or cancelled',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_week_plans_dates'), table_name='week_plans')
    op.drop_index(op.f('idx_week_plans_doctor'), table_name='week_plans')
    op.drop_index(op.f('idx_week_plans_patient'), table_name='week_plans')
    op.drop_index(op.f('idx_week_plans_status'), table_name='week_plans')
    op.create_index(op.f('ix_week_plans_plan_id'), 'week_plans', ['plan_id'], unique=False)
    op.drop_constraint(op.f('week_plans_patient_id_fkey'), 'week_plans', type_='foreignkey')
    op.drop_constraint(op.f('week_plans_doctor_id_fkey'), 'week_plans', type_='foreignkey')
    op.create_foreign_key(None, 'week_plans', 'users', ['patient_id'], ['user_id'])
    op.create_foreign_key(None, 'week_plans', 'users', ['doctor_id'], ['user_id'])
    op.drop_table_comment(
        'week_plans',
        existing_comment='Stores week-long workout plans created by doctors for patients',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'week_plans',
        'Stores week-long workout plans created by doctors for patients',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'week_plans', type_='foreignkey')
    op.drop_constraint(None, 'week_plans', type_='foreignkey')
    op.create_foreign_key(op.f('week_plans_doctor_id_fkey'), 'week_plans', 'users', ['doctor_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('week_plans_patient_id_fkey'), 'week_plans', 'users', ['patient_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_week_plans_plan_id'), table_name='week_plans')
    op.create_index(op.f('idx_week_plans_status'), 'week_plans', ['status'], unique=False)
    op.create_index(op.f('idx_week_plans_patient'), 'week_plans', ['patient_id'], unique=False)
    op.create_index(op.f('idx_week_plans_doctor'), 'week_plans', ['doctor_id'], unique=False)
    op.create_index(op.f('idx_week_plans_dates'), 'week_plans', ['start_date', 'end_date'], unique=False)
    op.alter_column('week_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status of the plan: active, completed, or cancelled',
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('week_plans', 'plan_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               comment='Name of the workout plan',
               existing_nullable=False)
    op.alter_column('week_plans', 'plan_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_unique_constraint(op.f('users_full_name_unique'), 'users', ['full_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_full_name'), 'users', ['full_name'], unique=False)
    op.drop_index(op.f('ix_session_details_detail_id'), table_name='session_details')
    op.drop_index(op.f('ix_schedules_schedule_id'), table_name='schedules')
    op.drop_index(op.f('ix_patient_notes_note_id'), table_name='patient_notes')
    op.alter_column('patient_notes', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.add_column('medical_records', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medical_records', type_='unique')
    op.drop_index(op.f('ix_medical_records_record_id'), table_name='medical_records')
    op.alter_column('medical_records', 'blood_type',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_exercise_logs_simple_user_id'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_exercise_logs_simple_id'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_exercise_logs_simple_date'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_combos_combo_id'), table_name='combos')
    op.drop_index(op.f('ix_combo_items_item_id'), table_name='combo_items')
    op.drop_index(op.f('ix_brain_exercise_sessions_session_id'), table_name='brain_exercise_sessions')
    op.drop_index(op.f('ix_brain_exercise_logs_log_id'), table_name='brain_exercise_logs')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_week_plan_id_fkey'), 'assignments', 'week_plans', ['week_plan_id'], ['plan_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assignments_patient_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.create_index(op.f('idx_assignments_week_plan'), 'assignments', ['week_plan_id'], unique=False)
    op.create_index(op.f('idx_assignments_day_of_week'), 'assignments', ['day_of_week'], unique=False)
    op.alter_column('assignments', 'rest_seconds',
               existing_type=sa.INTEGER(),
               comment='Rest time between sets in seconds',
               existing_nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('assignments', 'sets',
               existing_type=sa.INTEGER(),
               comment='Number of sets for this exercise',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('assignments', 'day_of_week',
               existing_type=sa.INTEGER(),
               comment='Day of week (1=Monday, 7=Sunday) for weekly plans',
               existing_nullable=True)
    op.alter_column('assignments', 'week_plan_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               comment='Reference to week plan if this assignment is part of a weekly plan',
               existing_nullable=True)
    op.create_table('notification_preferences',
    sa.Column('preference_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('push_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('in_app_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notification_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('preference_id', name=op.f('notification_preferences_pkey'))
    )
    op.create_table('detailed_plans',
    sa.Column('plan_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], name=op.f('detailed_plans_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], name=op.f('detailed_plans_patient_id_fkey')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('detailed_plans_pkey'))
    )
    # ### end Alembic commands ###
