"""Initial migration for SQLite

Revision ID: a89634392593
Revises: 
Create Date: 2026-03-30 16:12:18.352083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89634392593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=True)
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('brain_exercise_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_brain_exercise_logs_created_at'), 'brain_exercise_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_brain_exercise_logs_exercise_type'), 'brain_exercise_logs', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_brain_exercise_logs_log_id'), 'brain_exercise_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_brain_exercise_logs_user_id'), 'brain_exercise_logs', ['user_id'], unique=False)
    op.create_table('brain_exercise_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_brain_exercise_sessions_created_at'), 'brain_exercise_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_brain_exercise_sessions_exercise_type'), 'brain_exercise_sessions', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_brain_exercise_sessions_session_id'), 'brain_exercise_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_brain_exercise_sessions_user_id'), 'brain_exercise_sessions', ['user_id'], unique=False)
    op.create_table('combos',
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('combo_id')
    )
    op.create_index(op.f('ix_combos_combo_id'), 'combos', ['combo_id'], unique=False)
    op.create_index(op.f('ix_combos_doctor_id'), 'combos', ['doctor_id'], unique=False)
    op.create_table('exercise_logs_simple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('rep_count', sa.Integer(), nullable=False),
    sa.Column('session_duration', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_simple_created_at'), 'exercise_logs_simple', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_date'), 'exercise_logs_simple', ['date'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_exercise_type'), 'exercise_logs_simple', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_id'), 'exercise_logs_simple', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_simple_user_id'), 'exercise_logs_simple', ['user_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_date'), 'health_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_health_metrics_id'), 'health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_medical_records_record_id'), 'medical_records', ['record_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('receiver_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patient_notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_patient_notes_created_at'), 'patient_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_notes_doctor_id'), 'patient_notes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_notes_note_id'), 'patient_notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_patient_notes_patient_id'), 'patient_notes', ['patient_id'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedules_doctor_id'), 'schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_schedules_patient_id'), 'schedules', ['patient_id'], unique=False)
    op.create_index(op.f('ix_schedules_schedule_id'), 'schedules', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedules_start_time'), 'schedules', ['start_time'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_table('week_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_week_plans_doctor_id'), 'week_plans', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_week_plans_end_date'), 'week_plans', ['end_date'], unique=False)
    op.create_index(op.f('ix_week_plans_patient_id'), 'week_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_week_plans_plan_id'), 'week_plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_week_plans_start_date'), 'week_plans', ['start_date'], unique=False)
    op.create_index(op.f('ix_week_plans_status'), 'week_plans', ['status'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_workout_sessions_plan_id'), 'workout_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_start_time'), 'workout_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_workout_sessions_status'), 'workout_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('session_time', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('combo_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('week_plan_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.combo_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['week_plan_id'], ['week_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignments_assigned_date'), 'assignments', ['assigned_date'], unique=False)
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignments_combo_id'), 'assignments', ['combo_id'], unique=False)
    op.create_index(op.f('ix_assignments_doctor_id'), 'assignments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_assignments_exercise_type'), 'assignments', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_assignments_patient_id'), 'assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('combo_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=True),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.combo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_combo_items_item_id'), 'combo_items', ['item_id'], unique=False)
    op.create_table('session_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('reps_completed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('mistakes_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_session_details_detail_id'), 'session_details', ['detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_details_detail_id'), table_name='session_details')
    op.drop_table('session_details')
    op.drop_index(op.f('ix_combo_items_item_id'), table_name='combo_items')
    op.drop_table('combo_items')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_patient_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_exercise_type'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_doctor_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_combo_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_date'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_status'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_start_time'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_plan_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_week_plans_status'), table_name='week_plans')
    op.drop_index(op.f('ix_week_plans_start_date'), table_name='week_plans')
    op.drop_index(op.f('ix_week_plans_plan_id'), table_name='week_plans')
    op.drop_index(op.f('ix_week_plans_patient_id'), table_name='week_plans')
    op.drop_index(op.f('ix_week_plans_end_date'), table_name='week_plans')
    op.drop_index(op.f('ix_week_plans_doctor_id'), table_name='week_plans')
    op.drop_table('week_plans')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_start_time'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_schedule_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_patient_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_doctor_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_patient_notes_patient_id'), table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_note_id'), table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_doctor_id'), table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_created_at'), table_name='patient_notes')
    op.drop_table('patient_notes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medical_records_record_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_health_metrics_user_id'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_id'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_date'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index(op.f('ix_exercise_logs_simple_user_id'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_exercise_logs_simple_id'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_exercise_logs_simple_exercise_type'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_exercise_logs_simple_date'), table_name='exercise_logs_simple')
    op.drop_index(op.f('ix_exercise_logs_simple_created_at'), table_name='exercise_logs_simple')
    op.drop_table('exercise_logs_simple')
    op.drop_index(op.f('ix_combos_doctor_id'), table_name='combos')
    op.drop_index(op.f('ix_combos_combo_id'), table_name='combos')
    op.drop_table('combos')
    op.drop_index(op.f('ix_brain_exercise_sessions_user_id'), table_name='brain_exercise_sessions')
    op.drop_index(op.f('ix_brain_exercise_sessions_session_id'), table_name='brain_exercise_sessions')
    op.drop_index(op.f('ix_brain_exercise_sessions_exercise_type'), table_name='brain_exercise_sessions')
    op.drop_index(op.f('ix_brain_exercise_sessions_created_at'), table_name='brain_exercise_sessions')
    op.drop_table('brain_exercise_sessions')
    op.drop_index(op.f('ix_brain_exercise_logs_user_id'), table_name='brain_exercise_logs')
    op.drop_index(op.f('ix_brain_exercise_logs_log_id'), table_name='brain_exercise_logs')
    op.drop_index(op.f('ix_brain_exercise_logs_exercise_type'), table_name='brain_exercise_logs')
    op.drop_index(op.f('ix_brain_exercise_logs_created_at'), table_name='brain_exercise_logs')
    op.drop_table('brain_exercise_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
